apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  mysql-pvc
spec:
  storageClassName: mysqlStorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: mysqlStorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysqlData"
    type: DirectoryOrCreate