apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:5.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: rootdb-password
                  key: rootdb_password 
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: configmap-wp
                key: wp_user
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: configmap-wp
                key: wp_database
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db_password
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
    volumes:
      - name: mysql-storage
        persistantVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  annotations:
        prometheus.io/scrape: "true"
spec:
  selector:
    app: mysql-db
  type: NodePort
  ports:
    - port: 3306
      nodePort: 3306
      targetPort: mysql-port
      protocol: TCP