apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key
type: Opaque
data:
  aws_access_key: QUtJQTRNTUY2VUs3WEFYNTJHV0E=

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key
type: Opaque
data:
  aws_secret_access_key: SXpWeWRVbENTVXdGOUpxMUxYbDFFS1dzRWQzM3MzRmhBMDQ3L2d1SA==

---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  db_password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: rootdb-password
type: Opaque
data:
  rootdb_password: cGFzc3dvcmQ=
