apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        env:
        - name: WP_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-wp
              key: wp_host
        - name: WP_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap-wp
              key: wp_database
        - name: WP_DB_USER
          valueFrom:
            configMapKeyRef:
              name: configmap-wp
              key: wp_user
        - name: WP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: db_password
        ports:
        - containerPort: 80
          name: wp-port

---
apiVersion: v1
kind: Service
metadata:
  name: wp-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 80
    nodePort: 8088
    targetPort: wp-port
    protocol: TCP
  selector:
    app: wordpress
  type: NodePort




